sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm run lint
  - npm run test
  - npm run test-travis
  - npm run dist
after_success:
  - bash <(curl -s https://codecov.io/bash)
